### ISSUE TITLE
Question: Iterating over array elements 

### ISSUE THREAD

**Issue by dilipv21** [sdawood/json-tots#2]
Thanks for the tots !! it's very helpful in mapping JSONS !!

Query : Null check on array elements before ittirating. 

Document:
`
 {  
   "a" : 1,
   "b" : [ 
      { x :  10,
         y: 12
      },
     { x :  10,
         y: 12
      }]
 }
`

Template:
`
{ 
   "A" : {{a}},
   "B" : [
     "{%%{b}}",
      {  "X" : {{x}},
         "Y" : {{x}}
     }
  ]
}
`  

Scenario : When the Document doesn't have the "b" and if we try to transform it results in 
**_Error occurred while transforming data Error: Inception Operator [%] should be used for template nodes yielding an array_**.

Is there a way to check null or avoid above scenario ?
   
Thanks
Dilip

**Comment by sdawood** [comment]
Thanks for your report.

Off the top of my head, you can default 'b' from some named source, e.g. 'default'

I'll research better options and update soon.

For example:
var tots = require("json-tots")
const document =
{ "a" : 1, "bx" : [ { x : 10, y: 12 }, { x : 10, y: 12 }] }

const template =
{ "A" : '{{a}}', "B" : [ "{?=default %%{b}}", { "X" : '{{x}}', "Y" : '{{x}}' } ] }

const options = {sources: {default: {b: []}}}

const result = tots.transform(template, options)(document)

console.log(result)

**Comment by sdawood** [comment]
TIP

In general I recommend that you keep the options json that you use with a particular template transformation along with the template in the same versioned json text file.

Of course here we talk about the 'values' part of the options, with no runtime references.

You can merge later as such:

const options = {... loadedOptione, ... runtime options}

tots.transform(template, options)(document)

Hope that helps.

**Comment by dilipv21** [comment]
Thanks for the reponse.

I tried the above still didn't get the expected behaviour -

**Please find the executed code :**

`var tots = require("json-tots")
const document =
    { "a" : 1};
const template =
    { "A" : '{{a}}', "B" : [ "{%%{b}}", { "X" : '{{x}}', "Y" : '{{x}}' } ] };
const options = {sources: {default: {b: []}}};
const result = tots.transform(template, options)(document);
console.log(result);`
**Result**:

`Error: Inception Operator [%] should be used for template nodes yielding an array
    at`

**Comment by dilipv21** [comment]
Also, default to replace any element independent of json path.
