### ISSUE TITLE
Question: self-referencing templates

### ISSUE THREAD

**Issue by infinioo** [sdawood/json-tots#5]
How are self-referencing templates going to work and when do you think they will be available?

**Comment by sdawood** [comment]
Currently my thought process and my existing proof if concept goes like this:

You would #tag a node or a leaf
You would @tag mention the tagged element in another template leaf

Basic dependency resolution is applied and leaf rendering happens in order

I want to make it available along with async and stream references

Development is 60% done and would be available in a branch soon

Hang in there, tots 2.0 beta is coming soon

**Comment by sdawood** [comment]
Check current iteration in v2.x.x please
closes #5
