### ISSUE TITLE
used in production?

### ISSUE THREAD

**Issue by darrencruse** [sdawood/json-tots#7]
Hi just stumbled on json-tots looks interesting and potentially useful for a project I'm working on.

I was having a little trouble telling the status of json-tots?

Is it already being used would you consider it "production worthy"?

(also are your examples and tests from your README in the repo anywhere I don't see them? also are there any other examples than those in the README?)

Thanks,

Darren Cruse

**Comment by sdawood** [comment]
Hello Darren,

json-tots is open sourced from a production module, it is time tested and is used in many production projects by myself and my teams/colleagues.
There is already one other npm package that depends on json-tots.

Regarding the Examples, the README already points to the [tests](https://github.com/sdawood/json-tots/blob/master/src/transform.spec.js)
I follow javascript unit tests convention of having the test file next to the module-under-test with the same name but a postfix '.spec.js'

Don't hesitate to get in touch if you have further questions.

Regards,
Shady Dawood

**Comment by darrencruse** [comment]
Thanks Shady sounds gr8!!
